### ISSUE TITLE
With Github environment

### ISSUE THREAD

**Issue by cristipufu** [flutter-actions/setup-pubdev-credentials#1]
![image](https://github.com/flutter-actions/setup-pubdev-credentials/assets/3955285/63e32180-c8f4-444e-90a6-17c52675a890)

Is there a way to specify the Github environment? similar to `uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1`?

**Comment by socheatsok78** [comment]
Hi @cristipufu 

You can specify GitHub environment right within your workflow.

The `dart-lang/setup-dart/.github/workflows/publish.yml` is just a reusable workflow which the `environment` is automatically assigned to the reusable workflow from `workflow_call`'s inputs.

**Example**

```yaml
jobs:
  publish:
    name: 'Publish to pub.dev'
    environment: your environment goes here
    permissions:

```
